name: Lint, Check Types, Test
on: push

jobs:
  build:
    name: Lint, Check Types, Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn --frozen-lockfile
      - run: yarn eslint .
      - run: yarn tsc
      - run: yarn test
